# Form implementation generated from reading ui file 'iniciar_sesion.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Iniciar_Sesion(object):
    def setupUi(self, Iniciar_Sesion):
        Iniciar_Sesion.setObjectName("Iniciar_Sesion")
        Iniciar_Sesion.resize(400, 300)
        self.label = QtWidgets.QLabel(Iniciar_Sesion)
        self.label.setGeometry(QtCore.QRect(90, 90, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Iniciar_Sesion)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 61, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Iniciar_Sesion)
        self.pushButton.setGeometry(QtCore.QRect(100, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Iniciar_Sesion)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 250, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(Iniciar_Sesion)
        self.textEdit.setGeometry(QtCore.QRect(170, 80, 141, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Iniciar_Sesion)
        self.textEdit_2.setGeometry(QtCore.QRect(170, 150, 141, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_3 = QtWidgets.QLabel(Iniciar_Sesion)
        self.label_3.setGeometry(QtCore.QRect(150, 30, 81, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Iniciar_Sesion)
        QtCore.QMetaObject.connectSlotsByName(Iniciar_Sesion)

    def retranslateUi(self, Iniciar_Sesion):
        _translate = QtCore.QCoreApplication.translate
        Iniciar_Sesion.setWindowTitle(_translate("Iniciar_Sesion", "Dialog"))
        self.label.setText(_translate("Iniciar_Sesion", "Usuario:"))
        self.label_2.setText(_translate("Iniciar_Sesion", "Contraseña:"))
        self.pushButton.setText(_translate("Iniciar_Sesion", "Login"))
        self.pushButton_2.setText(_translate("Iniciar_Sesion", "Exit"))
        self.label_3.setText(_translate("Iniciar_Sesion", "INICIAR SESIÒN "))
